### ISSUE TITLE
Filter violations by account IDs

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/fullstop#103]
E.g.

~~~~
GET /violations?accounts=123456789,987654321
~~~~

Then I could start integrating fullstop into YOUR TURN. Maybe I could also provide the last violation ID known to me, so that I only get the rest.

~~~~
GET /violations?accounts=123456789,987654321&last_violation=1414
~~~~

**Comment by mrandi** [comment]
right now we already have an endpoint for that. Is not the same as what you requested.

```
GET /api/account-violations/{account_id}
```

we would like to add pagination ordered by time, but was not in plan to use a last_violation parameter.

**Comment by prayerslayer** [comment]
Re Endpoint: I’d have to filter by multiple account IDs because many people are in multiple teams.
Re Pagination: By time is okay too, I guess.

**Comment by mrandi** [comment]
I have wrote right now a small section to propose API changes.
Are you so kind to create a pull request with your changes?

here the link: https://github.com/zalando-stups/fullstop#propose-api-changes
