### ISSUE TITLE
Violation - Application version information are not completed

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#141]

**Comment by prayerslayer** [comment]
What exactly means "not completed"? Which fields are mandatory, which are not?

**Comment by prayerslayer** [comment]
Closing because already done: https://github.com/zalando-stups/fullstop/blob/%23141-incomplete-version-information/fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java#L163
