### ISSUE TITLE
Violation - No valid repository link

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#143]

**Comment by prayerslayer** [comment]
=> Repository URL in `scm-source.json` must belong to the same repository that is registered with the application in Kio.

**Comment by mrandi** [comment]
contains #142

**Comment by harti2006** [comment]
Implemented, but not yet tested and activated. Waiting for Kontrolletti to be ready.

**Comment by lotharschulz** [comment]
existance of `scm-source.json`in repo won't be checked by kontrolletti

**Comment by harti2006** [comment]
We are using Kontrolletti here to normalize SCM urls before we compare them.
E.g. `git@github.com:zalando-stups/fullstop.git` is equal to `https://github.com/zalando-stups/fullstop.git`

**Comment by Gregsen** [comment]
fixed with #252
