### ISSUE TITLE
Violation - The specification link is missing in commit message

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#145]
The link should also be valid.

Note:
We should bind kontrolletti to do that.

**Comment by Gregsen** [comment]
same as #252 ?

**Comment by kanuku** [comment]
@mrandi 
Kontrolletti must not check if the URL exists(http-call), this should not be part of kontrolletti. 
This would make the validation of commits trivial: A validation can fail because of different external factors, like when dependent services are not available or other causes.

**Comment by hjacobs** [comment]
Do we really really want URLs in commit messages? Personally, I will never write URLs in commit messages :imp:

**Comment by Gregsen** [comment]
Well, there has been some discussion wether URLs or custom shortname like `github:123` were better. And you don't have to use URLs, just live with the violation :smirk:

**Comment by mrandi** [comment]
@kanuku you are right, for that reason is an issue for fullstop ;)
But can you maybe explain if kontrolletti requires an url or also a short form to link the issue?

**Comment by Gregsen** [comment]
fixed with #252
