### ISSUE TITLE
Find if an instance is in (traffic > 0%)

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#18]
Find if an instance is in production mode (traffic > 0%)

**Comment by sarnowski** [comment]
How can we find out?

**Comment by mrandi** [comment]
Ideas:
* use auditing criticality level in kio
* use an additional flag in kio

Would be one of this option ok?

**Comment by mawenzel** [comment]
store switch in app app-version life cycle

**Comment by Gregsen** [comment]
merged into #82
