### ISSUE TITLE
collect all public interfaces (ELBs and public servers)

### ISSUE THREAD

**Issue by mawenzel** [zalando-stups/fullstop#238]
create a job that checks for every ELB and and other public facing servers

**Comment by harti2006** [comment]
## ELBs

1. filter scheme == internet-facing
1. filter subnet in dmz
1. check listeners
    * allowed ports: 443, 80
1. check security groups
    * allowed ports 443, 80
1. check unauthorized access
    * only if port 80 is allowed
        * then `GET http://<ip>:80/` MUST return a redirect 3xx AND Location MUST start with https://
    * if `GET https://<ip>:443/robots.txt` exists
        * then we assume, that this is a public website and does not need protection, e.g. tech blog, job portal, ...
        * else `GET https://<ip>:443/` MUST NOT return a successful status 2XX

## EC2 instances

1. filter subnet in dmz
1. check security groups
    * allowed ports 443, 80
1. check unauthorized access
    * only if port 80 is allowed
        * then `GET http://<ip>:80/` MUST return a redirect 3xx AND Location MUST start with https://
    * if `GET https://<ip>:443/robots.txt` exists
        * then we assume, that this is a public website and does not need protection, e.g. tech blog, job portal, ...
        * else `GET https://<ip>:443/` MUST NOT return a successful status 2XX

## Databases like RDS, DynamoDB, ElastiCache, Redshift

1. MUST NOT run dmz subnet

**Comment by sarnowski** [comment]
I don't like the "robots.txt" heuristic. If the robots.txt says "please do not index me, I am not supposed to be found" then this would tell us just that unprotected access is indeed allowed.

I would suggest a "is_public_endpoint" flag in Kio, which can be set by the App owner in YourTurn. We can then compare the Service URL and this flag to know, if we should create a violation for a found endpoint or not. This would be a whitelist approach where you, as an app owner, have explicitly tell the system that your intention is really to provide this endpoint to the public.

**Comment by hjacobs** [comment]
I like the "is_public_endpoint" idea in Kio, that's probably the cleaner approach.

**Comment by harti2006** [comment]
Makes sense. Removed the robots.txt parts from the spec. Will create a follow-up ticket...

**Comment by mrandi** [comment]
#243 follow up ticket for DB
