### ISSUE TITLE
Unprotected services

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#25]
At least hourly report (ideally, asap):
* All public IPs with an open port 443  (use https)
* All servers, that have a public IP and no security group at all.
* All servers, that have a public IP and ports besides 22 and 443 allowed as input.

Hints: security groups can be changed during runtime of a server

**Comment by jbellmann** [comment]
It is not possible to start instances without security-groups. So second point is obsolete.

**Comment by mrandi** [comment]
@jbellmann we should add the logic to check violations on security group changes.

maybe this can help: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSecurityGroup.html

**Comment by mrandi** [comment]
@jbellmann is the status of this issue correct?

**Comment by harti2006** [comment]
done with #238
