### ISSUE TITLE
Violations: Produce only violations that make sense

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/fullstop#254]
**As** Deploy engineer
**I want** to see violations that make sense
**So that** reduce violations count and make process much cleaner

**Examples**:
- Violations do not grouped by stack and they going to be created for every instance in stack
- Violations do not check already existing violation of same type in same scope (stack, version, etc.)
- Violations that depends of each other will be created any way, for instance only one has matter:
    - MISSING_VERSION_APPROVAL
    - VERSION_APPROVAL_NOT_ENOUGH
    - VERSION_APPROVAL_NOT_ENOUGH

**Comment by harti2006** [comment]
Sorry for the confusing violation types. We are going to spend the next weeks cleaning up the ambiguity  and add a lot more documentation to the violations.

**Comment by harti2006** [comment]
TODO: Merge VERSION_APPROVAL_NOT_ENOUGH into MISSING_VERSION_APPROVAL.
