### ISSUE TITLE
Violations: Support release stages workflow

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/fullstop#255]
**As** Release-engineer 
**I want** reduce redundant steps while deploying new version on release stage 
**So that** reduce deploy time for new version on release stage and keep me audit compliant

**Currently every single time when I deploy release stage I could receive a lot of violations:**
* APPLICATION_VERSION_NOT_PRESENT_IN_KIO
* MISSING_VERSION_APPROVAL
* VERSION_APPROVAL_NOT_ENOUGH
* EC2_WITH_A_SNAPSHOT_IMAGE

**To be audit compliant I should have no violations at all.**

**To deploy new version into release stage without violations I should:**
- *Manually create a version*
- *Approve the version version*
- *Ask at least one colleague to approve the version*
- **Make a deployment**
- *Go to violations and resolve EC2_WITH_A_SNAPSHOT_IMAGE manually*

**Unfortunately, only one of these steps makes sense for release stages**

**Comment by mrandi** [comment]
Hi @nsmolenskii,
right now there is no release stages workflow.
For that reason it's not possible to change this behaviour.

**Comment by nsmolenskii** [comment]
@mrandi  Seriously?  You close ticket just because there is no such abstraction? Instead keep it in mind and board as well?
