### ISSUE TITLE
Fix FULLSTOP_MANDATORY_APPROVALS metadata

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#257]
Metadata infromation are wrong, env variable is not evaluated.

**Comment by harti2006** [comment]
When declaring a property like this: `my.property = ${VALUE_FROM_ENV}` w/o specifying the env variable before the system starts, the property will be filled with the full string `"${VALUE_FROM_ENV}"`. Not sure if this is intended, or a bug.
A possible workaround would be to define a default value, which can be used if the env variable is absent:
`my.property = ${VALUE_FROM_ENV:foobar}`
