### ISSUE TITLE
docker images in pierone that are missing the “deployment.json”

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#27]
Find docker images in pierone that are missing the “deployment.json”

**Comment by sarnowski** [comment]
It's called 'scm-source.json': http://stups.readthedocs.org/en/latest/user-guide/application-development.html

**Comment by ljaeckel** [comment]
Waiting for @hjacobs  https://github.com/zalando-stups/pierone/issues/8

**Comment by mrandi** [comment]
@ljaeckel the endpoint is here!
