### ISSUE TITLE
Do not write violation on missing url

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#279]
A missing URL in Kio is not a reason for a violation.

**Comment by Gregsen** [comment]
@harti2006 same with [ApplicationMasterDataPlugin](https://github.com/zalando-stups/fullstop/blob/master/fullstop-plugins/fullstop-application-masterdata-plugin/src/main/java/org/zalando/stups/fullstop/plugin/ApplicationMasterdataPlugin.java#L107)?
