### ISSUE TITLE
Application that are use a wrong AMI

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#28]
Find application that are use a wrong AMI

**Comment by mrandi** [comment]
don't take care of NAT and Odd instances.

**Comment by hjacobs** [comment]
Do we already check the AMI owner (AWS account ID)? Only AMIs build by a "trusted" STUPS account should be allowed.

**Comment by mrandi** [comment]
yes. line 96
https://github.com/zalando-stups/fullstop/blob/master/fullstop-plugins/fullstop-ami-plugin/src/main/java/org/zalando/stups/fullstop/plugin/AmiPlugin.java

**Comment by hjacobs** [comment]
great! :-)
