### ISSUE TITLE
Version artifacts might have docker:// prefix

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/fullstop#280]
I labelled this as a bug, even though it behaves correctly now.

The bug is actually in YOUR TURN (zalando-stups/yourturn#363) where I don't save version artifacts with `docker://` prefix. (As there might be multiple types of deployment artifacts in the future.)

If we now fix this bug in YOUR TURN it would be cool if fullstop won't write violations for the actually correct behavior :blush:

**Comment by harti2006** [comment]
Fullstop can already handle both cases, with and without docker:// prefix. I just added a unit test to verify that.
