### ISSUE TITLE
Change SPEC_TYPE_IS_MISSING_IN_KIO to infer from specification_url

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/fullstop#309]
The specification type (GitHub issues, JIRA, ..) should be inferred from Kio's `specification_url`.

See https://github.com/zalando-stups/kio/issues/47

**Comment by mrandi** [comment]
`specification_url` is validated from kio as a valid URI.
We should than infer the URI and validate.

Types:
* paper
* jira
* github
* ..

**Comment by harti2006** [comment]
This should be implemented in Kio and not in Fullstop, because it should be possible for Kio users to see the spec type of applications.
