### ISSUE TITLE
Report usage of unapproves AWS services

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/fullstop#35]

**Comment by mrandi** [comment]
Any idea to how to find it out? Ask to every service will be not the best way.

Maybe call the billing service could be an easy solution but is for us ok to have this report once a day?

**Comment by mawenzel** [comment]
Cloudfront

**Comment by mawenzel** [comment]
combine with IAM policies

**Comment by mawenzel** [comment]
combine with IAM policies

**Comment by mrandi** [comment]
contained in #22

**Comment by mrandi** [comment]
@hjacobs @sarnowski @harti2006 
any idea how to do that? How can I evaluate Action, NotAction, Condition, Resources...

here the template code:
https://github.com/zalando-stups/fullstop/blob/d98e90883a9986851acfbd5b95062a0df40c9208/fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java#L118

**Comment by mrandi** [comment]
somehow included in #22
