### ISSUE TITLE
Violation if a team delete fullstop role in its team account

### ISSUE THREAD

**Issue by mawenzel** [zalando-stups/fullstop#354]
There should be a violation, if a team delete the ```fullstop``` role in its account. Currently we are getting only Exception because assume role fails.

**Comment by mrandi** [comment]
:+1:
@Gregsen @harti2006 what did you think about that?

**Comment by mrandi** [comment]
@Gregsen @harti2006 news here?

**Comment by Gregsen** [comment]
When we cannot connect to an account, can we be sure, that it's because of a deleted role? Is there some way to differentiate?

**Comment by mrandi** [comment]
@Gregsen Yes, we are getting a specific Exception

**Comment by harti2006** [comment]
seeing the Exceptions popping up on our monitor will create enough attention. In that cases we will fix this stuff asap.
Creating a violation for the respective account does maybe not show, how urgent this problem is.

**Comment by mrandi** [comment]
@mawenzel I will close this issue, right now is already solved via a process. If this happens again, you can reopen it and we will create also a violation.
