### ISSUE TITLE
Teams got wrong violations in case of odd host

### ISSUE THREAD

**Issue by mawenzel** [zalando-stups/fullstop#355]
There are some stuff provided from the STUPS team what has to run in the different team accounts. The upcoming violations are visible in youturn in the team "accounts".

For teams should be violations be visible which are belong to the teams and not what have to run in their account but is provided by an other team

**Comment by mrandi** [comment]
this is only a rule. duplicate with #348 
I will close this issue. Reopen it if I'm wrong.

**Comment by mawenzel** [comment]
Ok. But will this described a litte bit more detailed in the Issue  #348
<https://github.com/zalando-stups/fullstop/issues/348>

On Wed, Feb 10, 2016 at 4:19 PM, Michele Randi <notifications@github.com>
wrote:

> Closed #355 <https://github.com/zalando-stups/fullstop/issues/355>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando-stups/fullstop/issues/355#event-545901933>.
>



-- 

                                          _..-.
                                        .'     `\  __
                                       / a   )   \`  '-.
   .´ o)=-                            /   _,/    )      \
  /.-.'                              |= /| `---'       |\
 //  |\                              | |  \  \-.__\    / `
 ||  |'  Markus Wenzel              /_/   /  / / \ \  |
,:)_/_   producer cloud engineering      /__|_|  |_|__|
