### ISSUE TITLE
Violation if the root user have a active secret key xor no active mfa

### ISSUE THREAD

**Issue by tuxlife** [zalando-stups/fullstop#362]
There should be a violation, if the root user (`<root_account>`) have a active secret key (first violation) and MFA is not active (second violation)

Right configuration:

| user | mfa_active | access_key_1_active | access_key_2_active |
| --- | --- | --- | --- |
| `<root_account>` | **true** | **false** | **false** |

**Comment by mrandi** [comment]
I will create only one violation `UNSECURED_ROOT_USER`
All this violation should than be solved from stups.

**Comment by mrandi** [comment]
Not working, right now we can save only _one_ violation for every account and type combination.
