### ISSUE TITLE
Report IAM AccessKeys that are older than 1 week

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/fullstop#37]
Our policy requires access keys to be rotated at least once a week. Check all access keys:

http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListAccessKeys.html

http://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKeyMetadata.html
CreateDate > now-1week && status = active

**Comment by hjacobs** [comment]
I guess this check is quite important.

**Comment by mrandi** [comment]
@sarnowski With "access keys to be rotated" should we check (CreateDate > now-1week && status = active) for all manually added users right?
We need than any events to be triggered, but something like a job that every day is running, right?

**Comment by mrandi** [comment]
I spoked with @sarnowski.
* This check is only for manually added users (all IAM users) -> condition: CreateDate > now-1week && status = active
* this check is not correlated with aws events, we should run this check once a day, maybe in the evening/night
