### ISSUE TITLE
Add new heuristic Violation for IAM profiles or S3/SQS/… services that enable cross account access

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#372]
### Expected behavior
Produce a violation if roles or services enable cross account access

### Step needed
* Analyze new IAM events if they are created with cross account access
* scan s3 policy
* scan SQS policy
*…

### Dependencies
* no DB dependency should be necessary

**Comment by sarnowski** [comment]
* There shouldn't be any trust relationships anywhere.
* Every policy, that contains somehow an account number that does not match the local account, a violation should come up.

**Comment by mrandi** [comment]
@sarnowski would be than this a good way?

* fetch all accounts ids  (A,B,C,D,…,Z)
* go through all policies in account A and see if one the policies contains B,C,…,Z
* than go to account B and see if contains A,C,D,…,Z

and this for all accounts?

What about external accounts?

Would be better to use  regexp that search for accounts ids that are not the same account which I'm doing the check?

**Comment by mrandi** [comment]
obsolete, will be solved from another tool.
