### ISSUE TITLE
?checked=true not working well

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#378]
### Expected behavior

Only manually resolved violations should return. Right now we add a comment by whitelisting.
We will need to add the ruleid is null conditions or avoid to add a comment when we whitelist a violation.

### Step needed

* add the ruleId is null conditions ( ?checked=true -> comment not null and ruleId is null )

or
* remove the comment by whitelisting

### Dependencies

**Comment by mrandi** [comment]
@harti2006 @Gregsen which option would be the best one?

**Comment by harti2006** [comment]
I personally would not "remove the comment by whitelisting", because this is our compatibility feature.
Instead I would set (whitelisted = false) as a default in the API

**Comment by mrandi** [comment]
:+1: ok! fine with that!
