### ISSUE TITLE
Report if IAM users have or use passwords

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/fullstop#38]
Passwords are not allowed.

http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUsers.html
http://docs.aws.amazon.com/IAM/latest/APIReference/API_User.html
PasswordLastUsed != null

**Comment by hjacobs** [comment]
+1

**Comment by mrandi** [comment]
* This check is only for manually added users (all IAM users) -> condition: PasswordLastUsed != null
* this check is not correlated with aws events, we should run this check once a day, maybe in the evening/night

similar as #37
