### ISSUE TITLE
Fullstop interprets application version as floating point number when checking with KIO.

### ISSUE THREAD

**Issue by i8r** [zalando-stups/fullstop#401]
The application version `6478e18` is interpreted as a number `6.478000000000001E21`. Thus one gets a `APPLICATION_VERSION_NOT_PRESENT_IN_KIO` because it cannot find `application_version: "6.478000000000001E21"` while `6478e18` is properly in KIO registered. Instead fullstop should thread the version number as opaque strings and not parse it.

**Comment by mrandi** [comment]
@i8r this is not a bug. I added tests to prove that.
you can simply use the yaml tags or quote your value.
