### ISSUE TITLE
Please allow whitelisting for specific checks based on the source docker image

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/fullstop#402]
### Expected behavior

No violations are reported if e.g. the application has an "unsecured endpoint" and the docker image has this check whitelisted.

**Comment by hjacobs** [comment]
@vetinari did you know that you can just flag the application as "publicly accessible" in YOUR TURN / Kio? This would already solve your problem (I guess) :smirk:

**Comment by harti2006** [comment]
fixed with #514
