### ISSUE TITLE
Provide a DELETE endpoint for white listing rules

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#417]
### Expected behavior
Rules should not actually be deleted, but the expiry date should be set.

### Step needed
Add an endpoint, e.g. `DELETE /api/whitelisting-rules/{id}?expiry_date=...`
It should take an optional parameter `expiry_date` that defaults to `now()` and MUST not lie in the past.

### Dependencies

**Comment by mrandi** [comment]
no more valid rule cannot be deleted.
expiry_date > now and the saved rule expiry_date > now
