### ISSUE TITLE
Remove log: Exception Processing ErrorPage

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#418]
Currently we are seeing a  lot of those lines in our logs:

```
ERROR [http-nio-8080-exec-137] o.a.c.c.C.[.[localhost] - Exception Processing ErrorPage[errorCode=0, location=/error]
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
```

### Expected behavior
Maybe we can set the log level for ClientAbortException to `OFF`

**Comment by mrandi** [comment]
https://github.com/spring-projects/spring-boot/issues/2001 maybe we should wait for this.
