### ISSUE TITLE
Missing severity of the violations in Fullstop list-violations.

### ISSUE THREAD

**Issue by pfigue** [zalando-stups/fullstop#434]
### Expected behavior

Fullstop provides not only the violation_type, but the severity of that violation.

### Step needed to reproduce the bug

`fullstop list-violations --accounts <number> -o tsv` provides no information about the severity of the violations, but only the `violation_type`. Sadly, I don't know the severity of each violation_type.

Same applies for `-o json` and `-o text`.

### Dependencies

None, AFAIK.

**Comment by ChristianLohmann** [comment]
@pfigue this also relates to the cli project of fullstop: [https://github.com/zalando-stups/fullstop-cli/](url)

**Comment by pfigue** [comment]
copied there. https://github.com/zalando-stups/fullstop-cli/issues/10
