### ISSUE TITLE
Deal with more than 2000 violations properly

### ISSUE THREAD

**Issue by rwitzel** [zalando-stups/fullstop#446]
Current behaviour:

fullstop --limit 5000 returns only 2000 entries if there are more than 3000 entries. And there is no information that are is internal limit of 2000.

Expected behaviour (variant A):

fullstop --limit 5000 returns up to 5000 entries if there are more than 3000 entries.

Expected behaviour (variant B):

fullstop --limit 5000 returns only 2000 entries if there are more than 3000 entries but informs about the maximum of 2000. fullstop --help informs about the limit as well.

Hint: https://github.com/spring-projects/spring-data-commons/search?utf8=%E2%9C%93&q=2000+in%3Afile+language%3Ajava&type=Code

**Comment by cgmv** [comment]
:+1:  on this issue

**Comment by harti2006** [comment]
@rwitzel I will close this issue here, as it is quite old. Feel free to file an issue for the [fullstop-cli](https://github.com/zalando-stups/fullstop-cli) (variant B).
