### ISSUE TITLE
Allow extra keys in scm-source.json

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/fullstop#449]
### Expected behavior

No violations raised with extra fields in the scm-source.json
### Step needed

add unkown field to the file

**Comment by hjacobs** [comment]
@vetinari can you move this to https://github.com/zalando-stups/pierone/issues ? Thanks!

**Comment by sarnowski** [comment]
I am opposed to custom fields as it prevents us from inventing new fields with a specific meaning in the future. Either those keys get namespaces or they are not allowed.

Namespacing could mean that custom keys need to be prefixed with `custom/` like `custom/myfield = foo`. That allows us to introduce fields later on without the danger of collisions.

**Comment by harti2006** [comment]
I will close this issue now, because it's old. Feel free to reopen again if still needed.
