### ISSUE TITLE
MODIFIED_ROLE_OR_SERVICE should contain diff

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#457]
### Expected behavior
Our roles are so complex, that it is not trivial to see small differences, when the MODIFIED_ROLE_OR_SERVICE violation occurs. It would be awesome to have a diff between the two json trees.

**Comment by harti2006** [comment]
This one looks promising:
https://github.com/flipkart-incubator/zjsonpatch

**Comment by mrandi** [comment]
I still like more the idea to push (from seven-second) a copy of the role in S3 and use the latest copy to run the checks.
This will also allow to have a history of all applied roles!

**Comment by harti2006** [comment]
Currently we have the situation, that the template is pushed to S3, but still the violation occurs. So somehow the template and the reality diverged. This issue just describes a small improvement about more information in the meta data. The history could still be achieved by S3 / seven-seconds github repo too which requires no bigger code changes.
