### ISSUE TITLE
Report "dirty" deployments

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#468]
### Expected behavior
Production Docker images must not be built from "dirty" (locally modified) git repositories.
The `"status"` property of Pierone's scm-source.json indicates if a docker image has been built from dirty sources. Fullstop should report a violation, if a deployment of such a dirty image happened.

**Comment by beytuel** [comment]
We want to see the following information for the violation: 

- Team ID 
- Application ID 
- Version 
- SCM Link 
- Creator 
- Date
- Instance ID
- Region
- Deployment Artifact

The priority of the violation should be 1.
