### ISSUE TITLE
Violations showing up in wrong accounts after application migration

### ISSUE THREAD

**Issue by sezeryilmaz** [zalando-stups/fullstop#482]
Sometimes after migrating an application from one account to another violations of that application get still assigned to the old account. The new owners of the application don't see the violations which can lead to security issues.

Please see TGC-43 and TGC-50 in techjira for examples.

**Comment by nehalium** [comment]
👍

**Comment by nehalium** [comment]
I'm willing to InnerSource this if possible. Can someone explain to me where the bug is?

**Comment by TomTomaso** [comment]
👍

**Comment by harti2006** [comment]
The problem is, that it's not trivial to track if an application has actually been shut down. I was hoping to roll out the new GitHub approval flow quicker and just delete the check for MISSING_SPEC_LINKS in Fullstop, as it has some drawbacks.

**Comment by nehalium** [comment]
That would be even better. Let me know if you need help with that.

**Comment by harti2006** [comment]
Switching to the new GitHub flow is up to each individual team. They need to apply and will get an invitation from Tech Controlling. Please refer to our internal docs (Rules of Play) for details.

**Comment by nehalium** [comment]
Oh, I see. You meant all teams need to switch to the Github flow. Do you recommend whitelisting our app then?

**Comment by harti2006** [comment]
@nehalium yes, whitelisting is currently the best solution

**Comment by ifadin** [comment]
:+1:

**Comment by nebulorum** [comment]
👍

**Comment by harti2006** [comment]
As I promised: With complete rollout of the GitHub approval flow, the violation type in question has been removed entirely. This issue won't pop up anymore.

**Comment by sezeryilmaz** [comment]
👍
