### ISSUE TITLE
Violation filtering does not work when resolving violations

### ISSUE THREAD

**Issue by rwitzel** [zalando-stups/fullstop#505]
`fullstop resolve-violations -t MY_VIOLATION_TYPE --applications MY_APPLICATION -s "MY COMMENT"`
should resolve the violations of given type.

But it resolved ALL violations of ALL types for my account.

**Comment by rwitzel** [comment]
Close because it was a false positive. Network hiccup or something like this.

**Comment by harti2006** [comment]
@rwitzel In case you need help to cleanup/undo the accidentally resolved violations, just write me a mail.
