### ISSUE TITLE
Report number of running applications per accounts

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/fullstop#82]
Relevant KPI: number of running applications (not instances nor application versions)

Applications "should" be registered in Kio, but this is not (yet) the case and even registered applications could be "inactive" (no running instance anywhere).

**Comment by hjacobs** [comment]
This requirement is important for Jan Löffler (Hanna), please contact him for details.

**Comment by mawenzel** [comment]
include issue #24

**Comment by Gregsen** [comment]
ToDo
- [ ] Application/ App-version life cycle. store in a new postgress table
- [ ] Track ec2 autoscaling events in DB as well
- [ ] Find if an instance is in production mode (traffic > 0%) (for discussion see #24)

**Comment by mrandi** [comment]
@Gregsen @harti2006 Can we move the last todo to another ticket? I'm also not sure if is a think we should do.
Can we than close it if is already finished?

**Comment by Gregsen** [comment]
:+1:
